---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
rm(list = ls())

africaLink="https://github.com/DACSS-Spatial/data_forSpatial/raw/refs/heads/main/WORLD/africa_8857.gpkg"
library(sf)
st_layers(africaLink)
```
```{r, message=FALSE}
africa <- st_read(africaLink, layer = "continent")
africaPopu_ddm <- st_read(africaLink, layer = "population_ddm")
africaPopu_psm <- st_read(africaLink, layer = "population_psm")

```

```{r}
st_crs(africa)$epsg
```

```{r}
library(ggplot2)
library(scales)

ggplot() +
  geom_sf(data = africa) +
  coord_sf(datum = st_crs(africa)) + 
  scale_x_continuous(labels = label_number(scale = 1/1000, suffix = " km")) +
scale_y_continuous(labels = label_number(scale = 1/1000, suffix = " km")) +
  labs(x = "Easting", y = "Northing")
```
```{r}
ggplot() + theme_light() +
  geom_sf(data = africa,fill="white",color="grey80") +
  geom_sf(data=africaPopu_ddm,
          alpha=0.1,
          shape=20,
          size=1,
          color="red")+
  coord_sf(datum = st_crs(africa)) 
  
```

```{r}
library(leaflet)
ddm_4326 <- st_transform(africaPopu_ddm, crs = 4326)
leaflet() %>%
  addTiles() %>%  
  addCircleMarkers(data = ddm_4326,
                   radius = 0.01,
                   opacity = 0.1)
```

```{r}

leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron)  %>%  
  addCircleMarkers(data = ddm_4326,
                   color="red",
                   radius = 0.01,
                   opacity = 0.1)
```

```{r}
psm_4326 <- st_transform(africaPopu_psm, crs = 4326)
leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron)  %>%  
  addCircleMarkers(data = psm_4326,
                   color="red", fillColor = "red",
                   label = ~Country,
                   radius = ~size/10)
```

```{r}
choro_4326 <- st_transform(africa, crs = 4326)
leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron)  %>%  
  addPolygons(data = choro_4326,
                   label = ~Country)
```
```{r}

```

